"""Build the professional item-build analytics page.

The page consumes a static cache generated by
``scripts/fetch/fetch_pro_builds.py``. It never connects to StarRocks at
runtime, which keeps credentials out of the browser and GitHub Pages.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

try:
    from . import site_common as _site
    from .hero_lab import _load_heroes, _load_items, _versions
except ImportError:
    import site_common as _site
    from hero_lab import _load_heroes, _load_items, _versions


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "pro_builds.json"
DETAIL_DATA_PATH = ROOT / "data" / "pro_builds_detail.json"
UPDATE_STATUS_PATH = ROOT / "data" / "pro_builds_update_status.json"
DIST = ROOT / "dist"
CORE_SCHEMA = "pro-builds-core-v2"


def _latest_href() -> str:
    try:
        meta = json.loads((ROOT / "data" / "site_meta.json").read_text(encoding="utf-8"))
        return meta.get("latest_patch_filename", "patches/7.41d.html")
    except Exception:
        return "patches/7.41d.html"


def _config() -> dict:
    version = _versions()[-1]
    heroes = _load_heroes(version)
    items = _load_items(version)
    return {
        "dataUrl": "data/pro_builds.json",
        "detailManifestUrl": "data/pro_builds_detail_manifest.json",
        "theoryPatch": version,
        "heroes": {
            h["id"]: {"name": h["name"], "icon": h["icon"]}
            for h in heroes
        },
        "items": {
            item["id"]: {
                "name": item["name"],
                "icon": item["icon"],
                "cost": item.get("cost", 0),
                "class": item.get("class", "regular"),
                "category": item.get("category"),
                "consumable": bool(item.get("consumable")),
                "bonus": {
                    key: value
                    for key, value in (item.get("bonus") or {}).items()
                    if isinstance(value, (int, float)) and abs(value) > 1e-9
                },
            }
            for item in items
        },
    }


def _write_detail_shards() -> dict | None:
    """Split the large detail cache into deterministic monthly static shards."""
    if not DETAIL_DATA_PATH.exists():
        return None
    core = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    detail = json.loads(DETAIL_DATA_PATH.read_text(encoding="utf-8"))
    month_by_match = {
        str(row.get("m")): str(row.get("d") or "unknown")[:7]
        for row in core.get("records", [])
        if row.get("m") is not None
    }
    shards: dict[str, dict] = {}

    def bucket_for(match_id) -> tuple[str, dict]:
        month = month_by_match.get(str(match_id), "unknown")
        shard = shards.setdefault(
            month, {"meta": {"month": month}, "players": {}, "drafts": {}, "events": {}}
        )
        return month, shard

    for key, value in (detail.get("players") or {}).items():
        match_id = str(key).split(":", 1)[0]
        bucket_for(match_id)[1]["players"][key] = value
    for section in ("drafts", "events"):
        for match_id, value in (detail.get(section) or {}).items():
            bucket_for(match_id)[1][section][str(match_id)] = value

    shard_dir = DIST / "data" / "pro_builds_detail"
    if shard_dir.exists():
        shutil.rmtree(shard_dir)
    shard_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "version": 1,
        "generated_at": detail.get("meta", {}).get("generated_at"),
        "bucket_key": "record date YYYY-MM",
        "buckets": {},
    }
    for month in sorted(shards):
        shard = shards[month]
        match_ids = {
            key.split(":", 1)[0] for key in shard["players"]
        } | set(shard["drafts"]) | set(shard["events"])
        shard["meta"].update(
            {
                "matches": len(match_ids),
                "players": len(shard["players"]),
                "draft_matches": len(shard["drafts"]),
                "event_matches": len(shard["events"]),
            }
        )
        target = shard_dir / f"{month}.json"
        target.write_text(
            json.dumps(shard, ensure_ascii=False, separators=(",", ":")),
            encoding="utf-8",
        )
        manifest["buckets"][month] = {
            "url": f"data/pro_builds_detail/{month}.json",
            "bytes": target.stat().st_size,
            **shard["meta"],
        }
    manifest_path = DIST / "data" / "pro_builds_detail_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    legacy = DIST / "data" / DETAIL_DATA_PATH.name
    if legacy.exists():
        legacy.unlink()
    return manifest


def _write_compact_core() -> dict:
    """Dictionary-encode repeated core fields for a substantially smaller first request."""
    payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    source_rows = payload.get("records") or []
    dictionary_fields = ("d", "p", "l", "t", "s", "n", "h", "rm", "item")
    dictionaries: dict[str, list[str]] = {field: [] for field in dictionary_fields}
    indexes: dict[str, dict[str, int]] = {field: {} for field in dictionary_fields}

    def encode(field: str, value) -> int:
        text = "" if value is None else str(value)
        index = indexes[field].get(text)
        if index is None:
            index = len(dictionaries[field])
            indexes[field][text] = index
            dictionaries[field].append(text)
        return index

    records = []
    for row in source_rows:
        encoded_items = []
        for pair in (row.get("i") or []):
            encoded_items.extend(
                [encode("item", pair[0]), pair[1] if len(pair) > 1 else None]
            )
        encoded_uses = None if row.get("u") is None else []
        if encoded_uses is not None:
            for pair in row.get("u"):
                encoded_uses.extend(
                    [encode("item", pair[0]), pair[1] if len(pair) > 1 else None]
                )
        records.append(
            [
                row.get("m"), encode("d", row.get("d")), encode("p", row.get("p")),
                row.get("li"), encode("l", row.get("l")), encode("t", row.get("t")),
                encode("s", row.get("s")), encode("n", row.get("n")),
                encode("h", row.get("h")), row.get("hi"), row.get("sl"),
                row.get("tm"), row.get("r"), encode("rm", row.get("rm")),
                row.get("rc"), row.get("w"), row.get("lv"), row.get("nw"),
                row.get("du"), encoded_items, row.get("g"), encoded_uses,
            ]
        )
    meta = dict(payload.get("meta") or {})
    if UPDATE_STATUS_PATH.exists():
        try:
            meta["update_status"] = json.loads(UPDATE_STATUS_PATH.read_text(encoding="utf-8"))
        except (OSError, ValueError, json.JSONDecodeError):
            meta["update_status"] = {"status": "invalid", "error": "更新状态文件不可读取"}
    else:
        meta["update_status"] = {"status": "baseline", "completed_at": meta.get("generated_at")}
    compact = {
        "schema": CORE_SCHEMA,
        "meta": meta,
        "dictionaries": dictionaries,
        "records": records,
    }
    target = DIST / "data" / DATA_PATH.name
    target.write_text(
        json.dumps(compact, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    return {
        "path": target,
        "source_bytes": DATA_PATH.stat().st_size,
        "bytes": target.stat().st_size,
        "records": len(records),
        "dictionary_counts": {key: len(value) for key, value in dictionaries.items()},
    }


def render_html() -> str:
    config = json.dumps(_config(), ensure_ascii=False, separators=(",", ":"))
    config = config.replace("<", "\\u003c")
    nav = _site.render_top_nav(
        "materials", _latest_href(), subtabs_active="pro_builds", subnav_in_header=False
    )
    subnav = _site.render_materials_subnav("pro_builds")
    av = _site.compute_asset_version()
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SIKLE | Pro Build Analytics</title>
{_site.favicon_links()}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Jersey+10&family=Jersey+25&display=block">
<link rel="stylesheet" href="styles.css?v={av}">
</head>
<body class="pro-builds-body">
{nav}
<div class="container pro-builds-page">
{subnav}
<main class="pb-main">
  <header class="pb-hero">
    <div>
      <span class="pb-eyebrow">PRO MATCHES × HERO LAB</span>
      <h1>职业选手出装分析</h1>
      <p>围绕英雄出装研究、选手英雄研究和赛前准备组织职业比赛数据，将完整路线、购买时点、比赛情境与 Hero Lab 理论属性放在同一条研究动线中。</p>
    </div>
    <div class="pb-hero-status"><div class="pb-data-note" id="pb-data-note">正在加载职业比赛缓存…</div><div class="pb-freshness" id="pb-freshness" role="status">正在检查数据新鲜度…</div></div>
  </header>

  <section class="pb-research-picker" aria-label="选择研究方向">
    <header><span>先选择你要回答的问题</span><small>系统会自动整理筛选项并打开最相关的分析结果</small></header>
    <div class="pb-research-modes">
      <button type="button" data-pb-mode="hero" aria-pressed="true"><b>英雄出装研究</b><span>这个英雄当前怎么出、何时出、路线如何变化</span></button>
      <button type="button" data-pb-mode="player" aria-pressed="false"><b>选手英雄研究</b><span>某位选手使用特定英雄时的完整路线与个人偏好</span></button>
      <button type="button" data-pb-mode="scout" aria-pressed="false"><b>赛前准备</b><span>研究目标战队或选手在阵容、局势和版本中的选择</span></button>
    </div>
  </section>

  <section class="pb-filter-panel" aria-label="分析筛选器">
    <header class="pb-filter-heading">
      <div><span>RESEARCH SETUP</span><h2 id="pb-mode-title">英雄出装研究</h2><p id="pb-mode-description">先选英雄和时间，直接查看职业比赛中的完整出装路线。</p></div>
      <button type="button" id="pb-advanced-toggle" aria-controls="pb-advanced-filters" aria-expanded="false">高级筛选与工具</button>
    </header>
    <div class="pb-core-filters" id="pb-core-filters">
      <label data-pb-field="patch"><span>版本</span><select id="pb-patch"><option value="">全部版本</option></select></label>
      <label data-pb-field="from"><span>开始日期</span><input id="pb-date-from" type="date"></label>
      <label data-pb-field="to"><span>结束日期</span><input id="pb-date-to" type="date"></label>
      <label data-pb-field="league"><span>赛事</span><select id="pb-league"><option value="">全部赛事</option></select></label>
      <label data-pb-field="team"><span>战队</span><input id="pb-team-search" type="search" list="pb-team-options" autocomplete="off" placeholder="搜索战队" aria-label="搜索战队"><datalist id="pb-team-options"></datalist><select id="pb-team" hidden><option value="">全部战队</option></select></label>
      <label data-pb-field="player"><span>选手</span><input id="pb-player-search" type="search" list="pb-player-options" autocomplete="off" placeholder="搜索选手" aria-label="搜索选手"><datalist id="pb-player-options"></datalist><select id="pb-player" hidden><option value="">全部选手</option></select></label>
      <label data-pb-field="hero"><span>英雄</span><input id="pb-hero-search" type="search" list="pb-hero-options" autocomplete="off" placeholder="搜索英雄" aria-label="搜索英雄"><datalist id="pb-hero-options"></datalist><select id="pb-hero-select" hidden><option value="">全部英雄</option></select></label>
      <label data-pb-field="role" title="职责位置由本届联赛的主分路 lane_role 与补刀聚合计算；slot 不参与判位"><span>职责位置</span><select id="pb-role"><option value="">全部位置</option><option value="1">1号位</option><option value="2">2号位</option><option value="3">3号位</option><option value="4">4号位</option><option value="5">5号位</option></select></label>
      <label data-pb-field="result"><span>结果</span><select id="pb-result"><option value="">全部结果</option><option value="1">胜利</option><option value="0">失败</option></select></label>
      <label data-pb-field="situation"><span>15分钟局势</span><select id="pb-situation"><option value="">全部局势</option><option value="ahead">优势（经济领先 ≥1500）</option><option value="even">均势（±1500）</option><option value="behind">劣势（经济落后 ≥1500）</option></select></label>
      <label data-pb-field="opponent"><span>对手英雄</span><input id="pb-opponent-search" type="search" list="pb-opponent-options" autocomplete="off" placeholder="搜索对手英雄" aria-label="搜索对手英雄"><datalist id="pb-opponent-options"></datalist><select id="pb-opponent" hidden><option value="">全部对手</option></select></label>
      <label data-pb-field="method"><span>判位方法</span><select id="pb-role-method"><option value="">全部方法</option><option value="lanes">分路 + 补刀</option><option value="hits">纯补刀兜底</option></select></label>
      <label data-pb-field="scope"><span>物品范围</span><select id="pb-scope"><option value="core">核心成装</option><option value="regular">全部常规物品</option><option value="all">含消耗品/中立物品</option></select></label>
    </div>
    <div class="pb-primary-actions"><button type="button" class="pb-run-analysis" id="pb-run-analysis">查看英雄出装路线</button><button type="button" data-pb-range="30">最近30天</button><button type="button" data-pb-range="90">最近90天</button></div>
    <div id="pb-advanced-filters" class="pb-advanced" hidden>
      <div class="pb-advanced-grid" id="pb-advanced-grid"></div>
      <div class="pb-filter-actions"><button type="button" class="pb-reset" id="pb-reset">重置筛选</button><button type="button" id="pb-export-csv">导出 CSV</button><button type="button" id="pb-export-route">导出路线图</button><button type="button" id="pb-export-report">导出报告</button></div>
      <div class="pb-saved-views"><input id="pb-view-name" type="text" maxlength="48" placeholder="视图名称（可选）"><select id="pb-saved-view"><option value="">已保存的分析视图</option></select><button type="button" id="pb-save-view">保存当前</button><button type="button" id="pb-load-view">加载</button><button type="button" id="pb-delete-view">删除</button><span id="pb-view-status" aria-live="polite"></span></div>
    </div>
  </section>

  <section class="pb-analysis-context" id="pb-analysis-context" aria-label="当前分析条件">
    <div><span>当前研究</span><div class="pb-context-chips" id="pb-context-chips"></div></div>
    <strong id="pb-context-count">正在计算样本…</strong>
  </section>

  <section class="pb-kpis" aria-label="关键指标">
    <article><span>样本场次</span><strong id="pb-kpi-matches">—</strong></article>
    <article><span>选手-英雄局</span><strong id="pb-kpi-games">—</strong></article>
    <article><span>样本胜率</span><strong id="pb-kpi-winrate">—</strong></article>
    <article><span>职业选手</span><strong id="pb-kpi-players">—</strong></article>
    <article><span>英雄数</span><strong id="pb-kpi-heroes">—</strong></article>
  </section>
  <section class="pb-sample-guidance" id="pb-sample-guidance" hidden aria-live="polite"></section>

  <div class="pb-loading" id="pb-loading">正在汇总数据…</div>
  <nav class="pb-workspace-tabs" id="pb-workspace-tabs" aria-label="职业出装分析模块">
    <button type="button" data-pb-tab="overview">先看结论</button>
    <button type="button" data-pb-tab="routes" class="is-active">怎么出</button>
    <button type="button" data-pb-tab="people">谁这样出</button>
    <button type="button" data-pb-tab="situations">什么局势出</button>
    <button type="button" data-pb-tab="matches">真实比赛</button>
    <button type="button" data-pb-tab="quality">数据说明</button>
  </nav>
  <div class="pb-dashboard" id="pb-dashboard" hidden>
    <section class="pb-card pb-items-card" data-pb-panel="overview">
      <header><div><span class="pb-card-kicker">POPULARITY + TIMING</span><h2>热门成装</h2></div><small>点击物品查看理论属性</small></header>
      <div class="pb-table-wrap">
        <table class="pb-table"><thead><tr><th>物品</th><th>采用率</th><th>样本</th><th>胜率</th><th>情境校正</th><th>95%区间</th><th>中位时点</th><th title="从首次购买到第一次可识别主动使用或明确触发；纯被动装备显示为无数据">平均第一次使用间隔</th></tr></thead><tbody id="pb-items-body"></tbody></table>
      </div>
    </section>

    <aside class="pb-card pb-theory-card" id="pb-theory" data-pb-panel="overview">
      <header><div><span class="pb-card-kicker">HERO LAB</span><h2>理论属性</h2></div><small id="pb-theory-patch"></small></header>
      <div class="pb-empty">从左侧选择一个物品</div>
    </aside>

    <section class="pb-card pb-timing-card" data-pb-panel="overview">
      <header><div><span class="pb-card-kicker">ADOPTION CURVE</span><h2>购买时间分布</h2></div><small>累计完成比例</small></header>
      <div id="pb-timing-chart" class="pb-timing-chart"></div>
    </section>

    <section class="pb-card pb-sequence-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">BUILD PATHS</span><h2>英雄出装路线</h2></div><small id="pb-route-context">请选择英雄和比赛时间</small></header>
      <div id="pb-sequences" class="pb-sequences"></div>
    </section>

    <section class="pb-card pb-route-trend-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">ROUTE LIFECYCLE</span><h2>路线时效与版本演化</h2></div><small id="pb-route-trend-context">完整路线采用率，不拆成单件</small></header>
      <div class="pb-route-trend-controls"><label><span>观察粒度</span><select id="pb-route-trend-grain"><option value="week">按周</option><option value="month">按月</option><option value="patch">按版本</option></select></label><p>路线簇先在当前筛选范围内统一聚类，再比较各时间桶的采用率，避免每个时间桶重新聚类导致路线身份漂移。</p></div>
      <div id="pb-route-trends" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-flow-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">ROUTE FLOW</span><h2>路线流向图</h2></div><small>按购买顺序聚合，线宽代表样本量</small></header>
      <div id="pb-route-flow" class="pb-route-flow"></div>
    </section>

    <section class="pb-card pb-branch-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">DECISION BRANCHES</span><h2>分支出装树</h2></div><small>同类小件差异已合并；展开节点查看后续选择</small></header>
      <div id="pb-branch-tree" class="pb-branch-tree"></div>
    </section>

    <section class="pb-card pb-route-detail-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">CLUSTER DRILLDOWN</span><h2>路线簇详情</h2></div><small id="pb-route-cluster-version">点击上方路线簇查看组成</small></header>
      <div id="pb-route-detail" class="pb-route-detail"><div class="pb-empty">从“英雄出装路线”选择一个路线簇</div></div>
    </section>

    <section class="pb-card pb-recommend-card" data-pb-panel="overview">
      <header><div><span class="pb-card-kicker">DECISION ENGINE</span><h2>情境出装推荐</h2></div><small>基于当前筛选样本，不代表因果结论</small></header>
      <div id="pb-recommendation" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-compare-card" data-pb-panel="situations">
      <header><div><span class="pb-card-kicker">TIME WINDOW</span><h2>当前窗口 vs 前一窗口</h2></div><small id="pb-compare-context">自动使用等长前置时间窗</small></header>
      <div id="pb-comparison" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-situation-card" data-pb-panel="situations">
      <header><div><span class="pb-card-kicker">GAME STATE</span><h2>顺风 / 均势 / 逆风出装</h2></div><small>以15分钟团队经济差分组</small></header>
      <div id="pb-situations" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-matchup-card" data-pb-panel="situations">
      <header><div><span class="pb-card-kicker">MATCHUPS</span><h2>对手阵容与装备应对</h2></div><small>按对手英雄拆分采用率与样本胜率</small></header>
      <div id="pb-matchups" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-skill-card" data-pb-panel="situations">
      <header><div><span class="pb-card-kicker">SKILL × ITEM</span><h2>技能加点与出装联动</h2></div><small id="pb-detail-status">正在加载单局明细…</small></header>
      <div id="pb-skills" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-sub-card" data-pb-panel="routes">
      <header><div><span class="pb-card-kicker">ALTERNATIVES</span><h2>替代装备与时机评分</h2></div><small>同槽位互斥选择 + 当前样本购买百分位</small></header>
      <div id="pb-substitutions" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-coverage-card" data-pb-panel="quality">
      <header><div><span class="pb-card-kicker">DATA COVERAGE</span><h2>数据质量仪表盘</h2></div><small>覆盖率、缺失率、来源和月度健康度</small></header>
      <div id="pb-quality-summary" class="pb-analysis-grid"></div>
      <div id="pb-quality-table" class="pb-table-wrap"></div>
      <div id="pb-quality-source" class="pb-quality-source"></div>
    </section>

    <section class="pb-card pb-confidence-card" data-pb-panel="quality">
      <header><div><span class="pb-card-kicker">QUALITY</span><h2>样本可信度与判位覆盖</h2></div><small>Wilson 95% 区间；slot 从不参与判位</small></header>
      <div id="pb-confidence" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-players-card" data-pb-panel="people">
      <header><div><span class="pb-card-kicker">PLAYER SIGNATURE</span><h2>选手风格</h2></div><small>按英雄聚合的常见核心节点路线</small></header>
      <div class="pb-table-wrap">
        <table class="pb-table"><thead><tr><th>选手</th><th>战队</th><th>场次</th><th>总胜率</th><th>常见英雄 / 核心出装路线（购买中位 · 平均第一次使用间隔）</th><th>路线采用率</th><th>路线胜率</th></tr></thead><tbody id="pb-players-body"></tbody></table>
      </div>
    </section>

    <section class="pb-card pb-teams-card" data-pb-panel="people">
      <header><div><span class="pb-card-kicker">TEAM IDENTITY</span><h2>战队风格</h2></div><small>节奏、变体与代表物品</small></header>
      <div id="pb-teams" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-style-card" data-pb-panel="people">
      <header><div><span class="pb-card-kicker">STYLE FINGERPRINT</span><h2>选手风格画像与相似选手</h2></div><small>完全来自当前筛选内的出装、经济和路线数据</small></header>
      <div class="pb-style-controls"><label><span>分析选手</span><select id="pb-style-player"></select></label><p>六个维度均按当前样本中的选手分布标准化，不用于评价选手绝对实力。</p></div>
      <div class="pb-style-layout"><div id="pb-style-radar" class="pb-style-radar"></div><div id="pb-style-summary" class="pb-style-summary"></div></div>
      <div id="pb-style-similar" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-duel-card" data-pb-panel="people">
      <header><div><span class="pb-card-kicker">HEAD TO HEAD</span><h2>双选手 / 双版本对比</h2></div><small>其余顶部筛选条件保持生效</small></header>
      <div class="pb-duel-controls">
        <label><span>对比维度</span><select id="pb-duel-kind"><option value="player">选手</option><option value="patch">版本</option></select></label>
        <label><span>样本 A</span><select id="pb-duel-a"></select></label>
        <label><span>样本 B</span><select id="pb-duel-b"></select></label>
      </div>
      <div id="pb-duel-summary" class="pb-duel-summary"></div>
      <div id="pb-duel-items" class="pb-table-wrap"></div>
    </section>

    <section class="pb-card pb-alert-card" data-pb-panel="quality">
      <header><div><span class="pb-card-kicker">META WATCH</span><h2>新路线与时效提醒</h2></div><small>最近30天相对前30天</small></header>
      <div id="pb-alerts" class="pb-analysis-grid"></div>
    </section>

    <section class="pb-card pb-matches-card" data-pb-panel="matches">
      <header><div><span class="pb-card-kicker">MATCH EXPLORER</span><h2>单局明细</h2></div><small>点击一局查看技能、经济、事件和地图活动</small></header>
      <div class="pb-match-layout"><div class="pb-table-wrap"><table class="pb-table"><thead><tr><th>比赛 / 日期</th><th>选手</th><th>英雄</th><th>位置</th><th>15m经济差</th><th>结果</th></tr></thead><tbody id="pb-matches-body"></tbody></table></div><aside id="pb-match-detail" class="pb-match-detail"><div class="pb-empty">从左侧选择一局</div></aside></div>
    </section>

    <section class="pb-card pb-heatmap-card" data-pb-panel="matches">
      <header><div><span class="pb-card-kicker">MAP ACTIVITY</span><h2>英雄活动热力图</h2></div><small>5分钟快照坐标；选择英雄后更有意义</small></header>
      <div class="pb-heatmap-wrap"><canvas id="pb-heatmap" width="720" height="720"></canvas><div id="pb-heatmap-legend"></div></div>
    </section>
  </div>
  <aside class="pb-match-drawer" id="pb-match-drawer" hidden aria-label="真实比赛详情">
    <button type="button" class="pb-match-drawer-backdrop" data-pb-close-match aria-label="关闭比赛详情"></button>
    <section class="pb-match-drawer-panel">
      <header><div><span>REAL MATCH</span><strong>真实比赛复盘</strong></div><button type="button" data-pb-close-match>返回当前研究</button></header>
      <div id="pb-match-drawer-detail" class="pb-match-detail"><div class="pb-empty">正在加载比赛详情…</div></div>
    </section>
  </aside>
</main>
</div>
<script id="pro-builds-config" type="application/json">{config}</script>
<script defer src="src/scripts.js?v={av}"></script>
</body>
</html>
"""


def main() -> int:
    if not DATA_PATH.exists():
        raise SystemExit(
            "Missing data/pro_builds.json; run scripts/fetch/fetch_pro_builds.py first"
        )
    DIST.mkdir(exist_ok=True)
    (DIST / "data").mkdir(exist_ok=True)
    compact_core = _write_compact_core()
    detail_manifest = _write_detail_shards()
    html = render_html()
    (DIST / "pro_builds.html").write_text(html, encoding="utf-8")
    print(f"  -> dist/pro_builds.html: {len(html):,} bytes")
    saving = 1 - compact_core["bytes"] / max(1, compact_core["source_bytes"])
    print(
        f"  -> dist/data/pro_builds.json: {compact_core['bytes']:,} bytes "
        f"({saving:.1%} smaller than {compact_core['source_bytes']:,}-byte source)"
    )
    if detail_manifest:
        total = sum(row["bytes"] for row in detail_manifest["buckets"].values())
        print(f"  -> dist/data/pro_builds_detail/: {len(detail_manifest['buckets'])} monthly shards, {total:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
